<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.5">
  <POU Name="UpdateEventTimeStampWithSystemTime" Id="{3840351c-ebcc-4003-83c2-c5b7411c24f8}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION UpdateEventTimeStampWithSystemTime
VAR_INPUT
	stEvent : REFERENCE TO ST_Event;
END_VAR
VAR
	fbGETSYSTEMTIME : GETSYSTEMTIME;
	stFileTime : T_FILETIME;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbGETSYSTEMTIME(timeLoDW => stFileTime.dwLowDateTime,
				timeHiDW => stFileTime.dwHighDateTime);
				
stEvent.dtTimestamp := FILETIME_TO_DT(filetime := stFileTime);]]></ST>
    </Implementation>
    <LineIds Name="UpdateEventTimeStampWithSystemTime">
      <LineId Id="7" Count="0" />
      <LineId Id="12" Count="0" />
      <LineId Id="15" Count="1" />
    </LineIds>
  </POU>
</TcPlcObject>